name: flowgrid

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"  # Interfaz de gestión de RabbitMQ

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  # celery_worker:
  #   build: .
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
  #     - CELERY_RESULT_BACKEND=rpc://
  #   depends_on:
  #     - rabbitmq
